### ISSUE TITLE
Setup guidelines and env variables missing

### ISSUE THREAD

**Issue by Gourav-21** [RishabhJain0721/DormDeals-Backend#3]
## Problem 
Readme and setup guidelines of this backend are missing making it hard for the contributers to setup the project and start contributing

## suggestion
we should create a good readme with all the setup guidelines and env variables used in the project that would help contributers to setup and work the project easily

**Comment by RishabhJain0721** [comment]
Alright create the readme file. @Gourav-21

**Comment by alvin-dennis** [comment]
Assign this to me too as we are working together @RishabhJain0721
